spring.application.name=contact-management-api
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5430/contact_management_restful_api
spring.datasource.username=rizalamarulloh
spring.datasource.password=password


# Membuat atau memperbarui tabel otomatis berdasarkan class Java (Entity) Anda
spring.jpa.hibernate.ddl-auto=update

# Opsional: Memunculkan query SQL di console (sangat membantu buat belajar/debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true